(******************************************************************************)
(*                                                                            *)
(*                 Mīšarum: Debt Remission in Old Babylonian Law              *)
(*                                                                            *)
(*     Old Babylonian mīšarum edicts: qualifying agrarian debts are           *)
(*     remitted, debt-servants released, pledged holdings restored, and       *)
(*     merchant-credit obligations preserved as explicit exceptions.          *)
(*                                                                            *)
(*     "dannum enšam ana lā ḫabālim"                                          *)
(*     "That the strong might not oppress the weak."                          *)
(*     - Old Babylonian legal prologue, c. 18th century BCE                   *)
(*                                                                            *)
(*     Author: Repository maintainer                                          *)
(*     Date: March 8, 2026                                                    *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
